title: Let's Run Away Together
email: hi@charliegleason.com
description: >
  This is exciting.
  Look.
  New lines.
baseurl: "/lets-run-away-together"
url: "http://letsrunawaytogether.com"
twitter_username: superhighfives
github_username:  superhighfives

markdown: kramdown
exclude: [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "gulpfile.js",
  "package.json"
]