title: Let's Run Away Together
email: hi@charliegleason.com
description: >
  A music blog based somewhere between London and Melbourne
baseurl: "/lets-run-away-together"
url: "http://letsrunawaytogether.com"
twitter_username: superhighfives
github_username:  superhighfives

permalink: /:title

markdown: kramdown
exclude: [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "gulpfile.js",
  "package.json"
]