---
title: Let's Run Away Together
email: hi@charliegleason.com
description: |
  An art / design / music blog based somewhere between London and Melbourne.
baseurl: ''
url: https://letsrunawaytogether.com
permalink: /:title
defaults:
- scope:
    type: posts
  values:
    layout: "post"
    meta: "Enter your subtitle"
    categories: "N/A"
    meta_display: true
prose:
  rooturl: '_posts'
  siteurl: 'https://letsrunawaytogether.com'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "meta_display"
        field:
          element: "checkbox"
          label: "Display the subtitle?"
          value: true
      - name: "meta"
        field:
          element: "text"
          label: "Subtitle"
          placeholder: "So, what is the summary of the post?"
      - name: "categories"
        field:
          element: "text"
          label: "Categories"
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
